apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod
spec:
  containers:
  - name: my-app
    image: nginx
    volumeMounts:
    - mountPath: "/data"
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-pvc
